int	main()
{
	printf("subcategory: x\n");
	printf(" %#x \n", 0);
	printf(" %#x \n", -1);
	printf(" %#x \n", 1);
	printf(" %#x \n", 9);
	printf(" %#x \n", 10);
	printf(" %#x \n", 11);
	printf(" %#x \n", 15);
	printf(" %#x \n", 16);
	printf(" %#x \n", 17);
	printf(" %#x \n", 99);
	printf(" %#x \n", 100);
	printf(" %#x \n", 101);
	printf(" %#x \n", -9);
	printf(" %#x \n", -10);
	printf(" %#x \n", -11);
	printf(" %#x \n", -14);
	printf(" %#x \n", -15);
	printf(" %#x \n", -16);
	printf(" %#x \n", -99);
	printf(" %#x \n", -100);
	printf(" %#x \n", -101);
	printf(" %#x \n", INT_MAX);
	printf(" %#x \n", INT_MIN);
	printf(" %#x \n", LONG_MAX);
	printf(" %#x \n", LONG_MIN);
	printf(" %#x \n", UINT_MAX);
	printf(" %#x \n", ULONG_MAX);
	printf(" %#x \n", 9223372036854775807LL);
	printf(" %#x %#x %#x %#x %#x %#x %#x\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	printf(" %#x%#x \n", INT_MAX, INT_MIN);
	printf("subcategory: X\n");
	printf(" %#X \n", 0);
	printf(" %#X \n", -1);
	printf(" %#X \n", 1);
	printf(" %#X \n", 9);
	printf(" %#X \n", 10);
	printf(" %#X \n", 11);
	printf(" %#X \n", 15);
	printf(" %#X \n", 16);
	printf(" %#X \n", 17);
	printf(" %#X \n", 99);
	printf(" %#X \n", 100);
	printf(" %#X \n", 101);
	printf(" %#X \n", -9);
	printf(" %#X \n", -10);
	printf(" %#X \n", -11);
	printf(" %#X \n", -14);
	printf(" %#X \n", -15);
	printf(" %#X \n", -16);
	printf(" %#X \n", -99);
	printf(" %#X \n", -100);
	printf(" %#X \n", -101);
	printf(" %#X \n", INT_MAX);
	printf(" %#X \n", INT_MIN);
	printf(" %#X \n", LONG_MAX);
	printf(" %#X \n", LONG_MIN);
	printf(" %#X \n", UINT_MAX);
	printf(" %#X \n", ULONG_MAX);
	printf(" %#X \n", 9223372036854775807LL);
	printf(" %#X %#X %#X %#X %#X %#X %#X\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	printf(" %X ", 42);
	printf(" %X ", -42);
	printf("\n\nStarting...\n\n");
	ft_printf("subcategory: x\n");
	ft_printf(" %#x \n", 0);
	ft_printf(" %#x \n", -1);
	ft_printf(" %#x \n", 1);
	ft_printf(" %#x \n", 9);
	ft_printf(" %#x \n", 10);
	ft_printf(" %#x \n", 11);
	ft_printf(" %#x \n", 15);
	ft_printf(" %#x \n", 16);
	ft_printf(" %#x \n", 17);
	ft_printf(" %#x \n", 99);
	ft_printf(" %#x \n", 100);
	ft_printf(" %#x \n", 101);
	ft_printf(" %#x \n", -9);
	ft_printf(" %#x \n", -10);
	ft_printf(" %#x \n", -11);
	ft_printf(" %#x \n", -14);
	ft_printf(" %#x \n", -15);
	ft_printf(" %#x \n", -16);
	ft_printf(" %#x \n", -99);
	ft_printf(" %#x \n", -100);
	ft_printf(" %#x \n", -101);
	ft_printf(" %#x \n", INT_MAX);
	ft_printf(" %#x \n", INT_MIN);
	ft_printf(" %#x \n", LONG_MAX);
	ft_printf(" %#x \n", LONG_MIN);
	ft_printf(" %#x \n", UINT_MAX);
	ft_printf(" %#x \n", ULONG_MAX);
	ft_printf(" %#x \n", 9223372036854775807LL);
	ft_printf(" %#x %#x %#x %#x %#x %#x %#x\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	ft_printf(" %#x%#x \n", INT_MAX, INT_MIN);
	ft_printf("subcategory: X\n");
	ft_printf(" %#X \n", 0);
	ft_printf(" %#X \n", -1);
	ft_printf(" %#X \n", 1);
	ft_printf(" %#X \n", 9);
	ft_printf(" %#X \n", 10);
	ft_printf(" %#X \n", 11);
	ft_printf(" %#X \n", 15);
	ft_printf(" %#X \n", 16);
	ft_printf(" %#X \n", 17);
	ft_printf(" %#X \n", 99);
	ft_printf(" %#X \n", 100);
	ft_printf(" %#X \n", 101);
	ft_printf(" %#X \n", -9);
	ft_printf(" %#X \n", -10);
	ft_printf(" %#X \n", -11);
	ft_printf(" %#X \n", -14);
	ft_printf(" %#X \n", -15);
	ft_printf(" %#X \n", -16);
	ft_printf(" %#X \n", -99);
	ft_printf(" %#X \n", -100);
	ft_printf(" %#X \n", -101);
	ft_printf(" %#X \n", INT_MAX);
	ft_printf(" %#X \n", INT_MIN);
	ft_printf(" %#X \n", LONG_MAX);
	ft_printf(" %#X \n", LONG_MIN);
	ft_printf(" %#X \n", UINT_MAX);
	ft_printf(" %#X \n", ULONG_MAX);
	ft_printf(" %#X \n", 9223372036854775807LL);
	ft_printf(" %#X %#X %#X %#X %#X %#X %#X\n", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	ft_printf(" %X ", 42);
	ft_printf(" %X ", -42);

	return (0);
}