name: Inception
services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: ${DIR_NGINX}/Dockerfile
      args: 
        PUBK_NAME: ${PUBK_NAME}
        PUBK_NGINX: ${PUBK_NGINX}
        NGINX_CONF: ${NGINX_CONF}
        NGINX_CONF_NAME: ${NGINX_CONF_NAME}
        DIRKEY: ${DIRKEY}
        DIRCRT: ${DIRCRT}
        CERT_NAME: ${CERT_NAME}
        CERT_: ${CERT_}
        NGINX_DIR_DFLT_CONF: ${NGINX_DIR_DFLT_CONF}
        NGINX_DOMAIN_NAME: ${NGINX_DOMAIN_NAME}
        NGINX_DIRKEY: ${DIRKEY}/${CERT_KEY_NAME}
        TOOL_NGINX: ${TOOL_NGINX}
        BONUS: ${BONUS}
      no_cache: true
      secrets:
        - nginx_key
    ports:
      - 443:443
    hostname: ${NGINX_HOST_NAME}
    domainname: ${NGINX_DOMAIN_NAME}
    profiles: [nginx, all]
    networks:
      - back-tier
    volumes:
      - wp:/opt/nginx/wp

  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: ${DIR_MARIADB}/Dockerfile
      no_cache: true
      args:
        MDB_CNF_FL: ${MDB_CNF_FL}
        TOOL_CNF: ${TOOL_CNF}
        ADMN_USER: ${ADMN_USER}
        WDPRSS_USER: ${WDPRSS_USER}
      secrets:
        - mariadb_admin_key
        - mariadb_wdprss_key
    expose:
      - 3306
    profiles: [mariadb, all]
    networks:
      - back-tier
    volumes:
      - db:/opt/mysql/mysql/data

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: ${DIR_WP}/Dockerfile
      no_cache: true
      args:
        WP_PHAR: ${WP_PHAR}
        VS: ${VS}
        WP_CONF: ${WP_CONF}
        WP_CLI_CONFIG_PATH: ${WP_CLI_CONFIG_PATH}
        WP_INIT: ${WP_INIT}
      secrets:
        - mariadb_admin_key
        - mariadb_wdprss_key
    environment:
      BONUS: ${BONUS}
    expose:
      - 9000
    profiles: [wordpress, all]
    networks:
      - back-tier
    volumes:
      - wp:/opt/wordpress/
    depends_on:
      - mariadb

networks:
  back-tier:

secrets:
  nginx_key:
    file: ${CERT_KEY}
  mariadb_admin_key:
    environment: "ADMN_KEY"
  mariadb_wdprss_key:
    environment: "WDPRSS_KEY"

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_DIR}
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_DIR}
