server {
	listen  443 ssl;
	#Allowing only TLSv1.2, compulsory from subject.
	ssl_protocols   TLSv1.2 TLSv1.3;
	root			/opt/wordpress;

	location / {
		fastcgi_pass    wordpress:9000;
		include			/etc/nginx/fastcgi.conf;
		fastcgi_index   index.php;
	}

	location ~ \.(jpg|gif|png|webp|css)$ {
		root    /opt/nginx;
	}

	location ~* \.php$  {
		fastcgi_pass    wordpress:9000;
		include         /etc/nginx/fastcgi.conf;
	}

	error_page      500 502 503 504 /50x.html;
	location = /50x.html {
		root    /usr/share/nginx/html;
	}
}
